### ISSUE TITLE
Many different processes are spawned

### ISSUE THREAD

**Issue by mpickering** [idris-hackers/atom-language-idris#114]
I can't reliably reproduce this but after using the bindings for a while, 10s of different idris processes will be running. 

![image](https://cloud.githubusercontent.com/assets/1216657/15627531/2b6cad7e-24df-11e6-8ddb-edf685ce4146.png)

**Comment by pyrtsa** [comment]
+1. This keeps happening to me all the time now. I'm playing with the examples and exercises of Ch 9 of the TDD book, and after hitting the `^⌥A`, `^⌥C`, `^⌥M`, `^⌥T` and `^⌥R` key combinations a number of times, my computer goes very sluggish with dozens of `idris` processes using up all the available memory in Activity Monitor.

I don't really know how to reproduce the bug though, because I don't know how *not* to reproduce it!

(I'm using language-idris 0.4.4 with Idris 0.11.1, installed with Slack under `~/.local/bin` a few weeks ago, and with "Idris Location" respectively set up in language-idris settings.)

**Comment by pyrtsa** [comment]
Ok, here's a simple way to reproduce:

```idris
-- hello.idr
module Main

main : IO ()
main = putStrLn "Hello Atom!"
```

With that file, move the cursor on `putStrLn` and alternately hit `^⌥T` and `^⌥D` to see its type and documentation. Each time you switch from `^⌥T` to `^⌥D` or vice versa, a new `idris` process is spawned. If you keep hitting the same shortcut (e.g. `^⌥T`), it seems to reuse the last created process.

**Comment by archaeron** [comment]
hey
thanks a lot for reporting this and minimizing the example.
I'm writing my bachelors thesis atm. I should be finished soon, but soon after I'll have exams.
So I'm a bit swamped at the moment.

**Comment by justjoheinz** [comment]
I am afraid that this might be related to a fix where I attempted that windows which were closed are going to be reopened again. But this is just a guess.

https://github.com/idris-hackers/atom-language-idris/pull/96

**Comment by pyrtsa** [comment]
@justjoheinz No worries, I think it's unrelated. Please see the commits in #118.

**Comment by archaeron** [comment]
this should be fxed in v0.4.5 thanks to @pyrtsa
