### ISSUE TITLE
Repl should support :exec, :execute expr command

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#138]
The repl lets the programmer execute arbitrary expressions as long as they have a show instances.

Using this in the atom idris repl yields a reponse which seems to contain a path to an executable. The output of that executable needs to be piped back into the repl view.

Sample response from idris:
```
:run-program ["/var/folders/mq/b344w5kx4nv6ms0dd5vw45180000gn/T/idris14587779232007237709"]
0: "/var/folders/mq/b344w5kx4nv6ms0dd5vw45180000gn/T/idris14587779232007237709"
length: 1__proto__: Array[0]
```

**Comment by david-christiansen** [comment]
Yes, the output from these commands in IDE mode is a path to a temporary file that contains the generated executable. This is so that they can do IO actions with access to a real console, and to give the IDE the flexibility to run them how it wants. So in Emacs, they launch in new comint buffers, but another tool could also pop them up in a native terminal window, use whatever the local equivalent of comint is, or (in the simplest case) give the user a command to paste into a terminal.

**Comment by PhilAndrew** [comment]
Would like this fixed as the REPL is the nicest place to exec

**Comment by justjoheinz** [comment]
The issue is fixed for the time being, unfortunately I was not able to find a good package to support better feature support. Will address this again at a later time.
