### ISSUE TITLE
[request] better syntax highlighting

### ISSUE THREAD

**Issue by corazza** [idris-hackers/atom-language-idris#207]
At the moment the syntax highlighting seems quite inconsistent and it's hard to tell what it's trying to inform the user of. Many elements seem not to be picked up at all either, most of the code is just grey-ish.

**Comment by corazza** [comment]
it's kind of ridiculous

![screenshot from 2018-08-30 12-44-37](https://user-images.githubusercontent.com/1725635/44847092-a2988380-ac52-11e8-9b22-b428e531277e.png)

**Comment by corazza** [comment]
> If you want the highlighting as it is done by idris, I suggest using emacs.

Well most official resources point people towards using Atom, and I'd wager that only a fraction of people would consider worth it switching to an editor as different as Emacs just to get that.

And what do you mean by "as it is done by Idris"?

Also, I don't see how the output is influenced by the theme, the problem at hand is that highlighting is inconsistent and incomplete (with inconsistency being way worse a problem), not that I don't like the color scheme.

I'll assume that what you mean by "complete type checked program" you mean a scheme as to how I think it should be highlighted?

I wouldn't trust myself with that. There are people who thought more about this than I did. I can only point out that, at the moment, it seems inconsistent and incomplete.

> certainly be improved but comes with some pretty complicated regexp hacking

I think basically any small improvement would help, but I might be underestimating the work required. Still though, any language ever seems to have gotten this part right in Atom except Idris.

**Comment by justjoheinz** [comment]
idris tells an editor what is what, essentially how to do the syntax highlighting and where in the source file. But we cannot use this information currently in Atom, hence we need to write our own idris grammar for syntax highlighting which is difficult and we know that we do not get things right. 

You are very welcome to have a look at
https://github.com/idris-hackers/atom-language-idris/blob/master/grammars/language-idris.cson
and see if you can come up with improvements. 

I will close the issue for the time being, not because it is not justified, but there is no concrete task involved.

**Comment by corazza** [comment]
Btw a shot in the dark here: would it be possible to augment Atom's syntax highlighting mechanism inside the language-idris addon / set of addons / a new addon, so that Idris file syntax highlighting is relegated to the background language server that Emacs seems to use?

If I get what the issue is, this would seem like the better approach (uses an existing standard procedure), unless there are some Atom-specific barriers involved that I'm missing.

**Comment by justjoheinz** [comment]
Yes, in principle this would be possible and there were already issues raised here in the language-idris tracker and with the Atom community. But nothing came out of it to my knowledge, and implementing it myself is beyond what my spare time allows me. If you are interested: it would be an enourmous improvement for idris and atom and I would help digging in the archives.

**Comment by justjoheinz** [comment]
For starters:
https://github.com/idris-hackers/atom-language-idris/issues/10

**Comment by david-christiansen** [comment]
I tried to implement this once. The problem was that Atom didn't give an
API for programmatically changing faces - it allowed only setting
background colors, which wasn't very satisfying to use. So I dropped it.
They may have improved the plugin API since.

It seems possible to implement this using some sort of horrid z-index hack.
Not sure if it's worth the trouble, though. It seems like the kind of thing
that would be fragile in the face of Atom updates.

**Comment by corazza** [comment]
@justjoheinz At the moment I'm a bit too exhausted by uni work, and hacking Atom is not close enough to my current project path (in fact, learning Idris itself was also a huge digression, but that was pleasing and definitely worth it:D).

However Idris is just so amazing that I feel obligated to help out at least this way, so I will set a reminder and review in a month!

**Comment by archaeron** [comment]
@david-christiansen VSCode seems to think about it: https://github.com/Microsoft/vscode/wiki/Roadmap#editor
