### ISSUE TITLE
Potential syntax highlighting bug

### ISSUE THREAD

**Issue by CodingCellist** [idris-hackers/atom-language-idris#225]
I don't know if this is a bug, but I noticed that the syntax highlighting seems to change to the "case" highlighting when using a `case` expression in the function type definition.

![idris-syntax-highlighting](https://user-images.githubusercontent.com/26870380/50687220-b4cf6780-1020-11e9-806d-cf63c1ac544b.png)

**Comment by justjoheinz** [comment]
Sorry for the late reply. Syntax highlighting in Atom is a very feable attempt to get some highlighting, but it cannot make use of the semantic highlighting provided by the idris compiler (as it is e.g. used in the emacs idris mode). 

Your obeserved highlighting is kind of intentional in Atom, hence I close the issue.
